default:
  image: $CI_REGISTRY/flo/my-rust-runner:1.81-slim
  tags: [docker]
  cache:
    key: cargo-cache
    paths:
      - target/

stages:
  - build
  - test
  - publish

#sast:
#  stage: test

build:
  stage: build
  script:
    - cargo make -p ci-static-code-analysis-tasks
#  artifacts:
#    paths:
#      - target/release/basic

code-coverage:
  stage: test
  script:
    - cargo make code-coverage-xml
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/cobertura.xml
    
rustdoc:
  stage: publish
  script:
    - cargo make workspace-docs-flow
  artifacts:
    paths:
      - target/doc
  only:
    - main

#pages:
#  stage: publish
#  image: alpine
#  dependencies:
#    - build:amd64
#    - rustdoc
#  script:
#    - mkdir -p public
#    - mv target/doc public/doc
#    - mv target/release/basic
#  artifacts:
#    paths:
#      - public
#  only:
#    - main
