default:
  image: $CI_REGISTRY/flo/my-rust-runner/my-rust-runner:latest
  tags: [docker]
  cache:
    key: cargo-cache
    paths:
      - target/
      - ~/.cargo/registry
      - ~/.cargo/git
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

stages:
  - build
  - test
#  - publish

#sast:
#  stage: test

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/basic

tests:
  stage: test
  script:
    - cargo test
#rustdoc:
#  stage: build
#  script:
#    - cargo doc
#  artifacts:
#    paths:
#      - target/doc

#pages:
#  stage: publish
#  image: alpine
#  dependencies:
#    - build:amd64
#    - rustdoc
#  script:
#    - mkdir -p public
#    - mv target/doc public/doc
#    - mv target/release/basic
#  artifacts:
#    paths:
#      - public
#  only:
#    - main
