default:
  image: $CI_REGISTRY/flo/my-rust-runner:slim
  tags: [docker]
  cache:
    key: cargo-cache
    paths:
      - target/
      - ~/.cargo/registry
      - ~/.cargo/git

stages:
  - build
#  - test
#  - publish

#sast:
#  stage: test

build:
  stage: build
  script:
    - cargo make -p ci-static-code-analysis-tasks
#  artifacts:
#    paths:
#      - target/release/basic

#tests:
#  stage: test
#  script:
#    - cargo make test

#rustdoc:
#  stage: build
#  script:
#    - cargo doc
#  artifacts:
#    paths:
#      - target/doc

#pages:
#  stage: publish
#  image: alpine
#  dependencies:
#    - build:amd64
#    - rustdoc
#  script:
#    - mkdir -p public
#    - mv target/doc public/doc
#    - mv target/release/basic
#  artifacts:
#    paths:
#      - public
#  only:
#    - main
