name: evolution-lab

services:
    graphite-statsd:
        container_name: graphite
        restart: always
        ports:
            - 8081:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126
        volumes:
            - graphite-config:/opt/graphite/conf
            - graphite-data:/opt/graphite/storage
            - statsd-config:/opt/statsd/config
        image: graphiteapp/graphite-statsd

    grafana-enterprise:
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana-data:/var/lib/grafana
        image: grafana/grafana-oss

volumes:
    grafana-data:
    graphite-config:
    graphite-data:
    statsd-config: