[env]
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""

[config]
default_to_workspace = false

# Built-in task overrides
[tasks.pre-test]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.test-multi-phases-flow]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.post-test]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.coverage-tarpaulin.linux]
command = "cargo"
args = [
    "tarpaulin",
    "--all-features",
    "--skip-clean",
    "--workspace",
    "--out",
    "Xml",
    "--ignore-tests",
    "--output-dir",
    "target",
    "--target-dir",
    "target/tarpaulin-build",
]

# Dedicated tasks
[tasks.docker-build]
description = "Build docker image(s)"
command = "docker"
args = ["compose", "build"]

[tasks.local-up]
description = "Deploy app to local environment"
command = "docker"
args = ["compose", "up", "-d"]
dependencies = ["docker-build"]

[tasks.local-up-deps-only]
description = "Deploy deps to local environment"
command = "docker"
args = [
    "compose",
    "-f",
    "compose.yml",
    "-f",
    "compose.deps-only.yml",
    "up",
    "-d",
]

[tasks.local-down]
description = "Stop local environment"
command = "docker"
args = ["compose", "down"]
