[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.code-coverage-xml]
workspace = false
description = "Run code coverage (XML report)"
command = "cargo"
args = [
    "tarpaulin",
    "--all-features",
    "--workspace",
    "--out",
    "Xml",
    "--ignore-tests",
    "--output-dir",
    "target",
]

[tasks.code-coverage-html]
workspace = false
description = "Run code coverage (HTML report)"
command = "cargo"
args = [
    "tarpaulin",
    "--workspace",
    "--all-features",
    "--out",
    "Html",
    "--ignore-tests",
    "--output-dir",
    "target",
]

[tasks.workspace-docs]
install_crate = false
toolchain = "${CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN}"
command = "cargo"
args = ["doc", "--no-deps", "--workspace", "--all-features"]
