[env]
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""

[config]
default_to_workspace = false

[tasks.pre-test]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.test-multi-phases-flow]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.post-test]
condition = { env_false = ["CARGO_MAKE_CI"] }

[tasks.coverage-tarpaulin.linux]
command = "cargo"
args = [
    "tarpaulin",
    "--all-features",
    "--skip-clean",
    "--workspace",
    "--out",
    "Xml",
    "--ignore-tests",
    "--output-dir",
    "target",
    "--target-dir",
    "target/tarpaulin-build",
]
