[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
futures = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
