[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
genetic = { path = "../../genetic" }
futures = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
simple_logger = { workspace = true }
dipstick = "0.9.2"
